### ISSUE TITLE
Getting some socket timeouts

### ISSUE THREAD

**Issue by stack-engineering** [st3b1t/SatoshiTop#23]
#### Environment

- SatoshiTop version: (`$ npm info satop version`) : 2.5.1
- NodeJs version: (`$ node --version`) v18.19.1
- OS: (`grep VERSION /etc/os-release`) 
    VERSION_ID="24.04"
    VERSION="24.04 LTS (Noble Numbat)"
    VERSION_CODENAME=noble

#### Description Proposals or Problems

First of all, AWESOME TOOL. I've been looking for something like this forever. So thank you for writing it.

I'm not convinced this is an issue with satop, but wanted to post here anyway in case you had any ideas. I think the issue is probably something external in the OS that is cutting off the process. 

This issue is intermittent and inconsistent. The tool connects and displays just fine, but it will eventually stop and then throw the following error. One day I timed it and it was happening every 7 seconds consistently. But the past few days, the tool will run for 10 minutes, or even 30 minutes, before it happens. So I am wondering if it's performance related at the OS level.

Anyway I can troubleshoot? Checked /var/log/syslog and bitcoind debug.log but nothing sticks out.

Error: socket hang up
    at connResetException (node:internal/errors:720:14)
    at Socket.socketCloseListener (node:_http_client:474:25)
    at Socket.emit (node:events:529:35)
    at TCP.<anonymous> (node:net:351:12)

**Comment by st3b1t** [comment]
> #### Description Proposals or Problems
> First of all, AWESOME TOOL. I've been looking for something like this forever. So thank you for writing it.
many thanks!

did you contextually check the status of bitcoin-core rpc connection? because this `connResetException` could be caused by bitcoin-core side.

you should check if at the time it happens the bitcoin-core logs tell you anything, probably bitcoin closes the rpc connection for some reason(or a firewall getting in the middle)

try adding `debug=rpc` in `bitcoin.conf` for more verbosity
