### ISSUE TITLE
Multiple disks

### ISSUE THREAD

**Issue by smartm0use** [st3b1t/SatoshiTop#6]
Can you show percentage of used space for every disk in the system?

**Comment by st3b1t** [comment]
from version 2.0.2

**Comment by smartm0use** [comment]
Is it possible to add somewhere the label of the disk and/or its mount point?

**Comment by st3b1t** [comment]
> Is it possible to add somewhere the label of the disk and/or its mount point?

if you use larger screens you will see them appear... unfortunately there are impossible to fix limits of info displayed for small screens like a responsive web page.
(or you can decrease the terminal font size if you are in desktop environment)
![image](https://github.com/st3b1t/SatoshiTop/assets/113633676/ccda94cb-1544-4edc-bd8e-5a24eb27c050)
