### ISSUE TITLE
Memory usage per process

### ISSUE THREAD

**Issue by smartm0use** [st3b1t/SatoshiTop#7]
Can you show the percentage of memory used by single process in the system?

**Comment by st3b1t** [comment]
existed in an earlier version I took it out for space reasons... but it's actually useful information in a Bitcoin node
![Peek 2023-07-13 16-53](https://github.com/st3b1t/SatoshiTop/assets/113633676/39329047-b0c9-4091-bda9-23dac45a572b)

**Comment by st3b1t** [comment]
solved in https://github.com/st3b1t/SatoshiTop/releases/tag/v2.1.0

**Comment by smartm0use** [comment]
Maybe there is a glitch in visualizing user whose length is more than 4 characters?

![image](https://github.com/st3b1t/SatoshiTop/assets/5399265/ea7e6c8b-ce68-4daa-b780-7e4fd947e842)

**Comment by st3b1t** [comment]
yes.. it's a fucking nightmare to align text in ncurses.. for all screen sizes.

**Comment by st3b1t** [comment]
I'll probably make these values configurable from `.satoprc` file so anyone can adjust their view
https://github.com/st3b1t/SatoshiTop/blob/28b365d1efb9ca1aedbdae8fb8568480a7a1fbe0/lib/satop.js#L67
